/*
 * Farcaster Hub API
 *
 * Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.21.0
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PruneMessageBody {
    #[serde(rename = "message")]
    pub message: Box<models::Message>,
}

impl PruneMessageBody {
    pub fn new(message: models::Message) -> PruneMessageBody {
        PruneMessageBody {
            message: Box::new(message),
        }
    }
}

