/*
 * Farcaster Hub API
 *
 * Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.21.0
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignerMigratedEventBody {
    #[serde(rename = "migratedAt")]
    pub migrated_at: i64,
}

impl SignerMigratedEventBody {
    pub fn new(migrated_at: i64) -> SignerMigratedEventBody {
        SignerMigratedEventBody {
            migrated_at,
        }
    }
}

