/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NeynarNextFramePageMintUrl {
    /// The URL for minting, specific to the mint action.
    #[serde(rename = "mint_url")]
    pub mint_url: String,
}

impl NeynarNextFramePageMintUrl {
    pub fn new(mint_url: String) -> NeynarNextFramePageMintUrl {
        NeynarNextFramePageMintUrl {
            mint_url,
        }
    }
}

