/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCastReqBodyEmbedsCastIdProperties {
    /// The unique identifier of a farcaster user (unsigned integer)
    #[serde(rename = "fid")]
    pub fid: i32,
    #[serde(rename = "hash")]
    pub hash: String,
}

impl PostCastReqBodyEmbedsCastIdProperties {
    pub fn new(fid: i32, hash: String) -> PostCastReqBodyEmbedsCastIdProperties {
        PostCastReqBodyEmbedsCastIdProperties {
            fid,
            hash,
        }
    }
}

