/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscriptions {
    #[serde(rename = "subscriptions_created")]
    pub subscriptions_created: Vec<models::Subscription>,
}

impl Subscriptions {
    pub fn new(subscriptions_created: Vec<models::Subscription>) -> Subscriptions {
        Subscriptions {
            subscriptions_created,
        }
    }
}

