/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserVerifiedAddressesPrimary {
    /// Ethereum address
    #[serde(rename = "eth_address")]
    pub eth_address: String,
    /// Solana address
    #[serde(rename = "sol_address")]
    pub sol_address: String,
}

impl UserVerifiedAddressesPrimary {
    pub fn new(eth_address: String, sol_address: String) -> UserVerifiedAddressesPrimary {
        UserVerifiedAddressesPrimary {
            eth_address,
            sol_address,
        }
    }
}

