/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeployFungibleReqBodyMetadataMedia {
    /// Media file associated with the token.  Supported formats are image/jpeg, image/gif and image/png 
    Binary(Vec<u8>),
    /// URI of the media file
    URI(String),
}

impl Default for DeployFungibleReqBodyMetadataMedia {
    fn default() -> Self {
        Self::Binary(Default::default())
    }
}

