/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrameCatalogResponse {
    #[serde(rename = "frames")]
    pub frames: Vec<models::FrameV2WithFullAuthor>,
    #[serde(rename = "next")]
    pub next: Box<models::NextCursor>,
}

impl FrameCatalogResponse {
    pub fn new(frames: Vec<models::FrameV2WithFullAuthor>, next: models::NextCursor) -> FrameCatalogResponse {
        FrameCatalogResponse {
            frames,
            next: Box::new(next),
        }
    }
}

