/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NeynarNextFramePageRedirect {
    /// The URL to redirect to.
    #[serde(rename = "redirect_url")]
    pub redirect_url: String,
}

impl NeynarNextFramePageRedirect {
    pub fn new(redirect_url: String) -> NeynarNextFramePageRedirect {
        NeynarNextFramePageRedirect {
            redirect_url,
        }
    }
}

