/*
 * Farcaster API V2
 *
 * The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 
 *
 * The version of the OpenAPI document: 2.33.1
 * Contact: team@neynar.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCastResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "cast")]
    pub cast: Box<models::PostCastResponseCast>,
}

impl PostCastResponse {
    pub fn new(success: bool, cast: models::PostCastResponseCast) -> PostCastResponse {
        PostCastResponse {
            success,
            cast: Box::new(cast),
        }
    }
}

