name: Publish Rust Crates

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish neynar_sdk
        working-directory: ./generated/api
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          echo "Publishing neynar_sdk..."
          cargo publish --allow-dirty
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select(.name=="neynar_sdk") | .version')
          git tag "neynar-sdk-v$VERSION"
          git push origin "neynar-sdk-v$VERSION"

      - name: Publish neynar_hub_sdk
        working-directory: ./generated/hub-api
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          echo "Publishing neynar_hub_sdk..."
          cargo publish --allow-dirty
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select(.name=="neynar_hub_sdk") | .version')
          git tag "neynar-hub-sdk-v$VERSION"
          git push origin "neynar-hub-sdk-v$VERSION"